services:
  vushf-exporter:
    image: jonikahara/vushf-exporter
    logging:
      driver: json-file
      options:
        max-size: '50m'
        max-file: 5
    ports:
      - '9108:9108'
    restart: always
