services:
  vushf-exporter:
    image: ghcr.io/kahara/vushf-exporter:latest
    logging:
      driver: json-file
      options:
        max-size: '50m'
        max-file: 5
    ports:
      - '9108:9108'
      - '8071:8071'
    restart: always
