{
 "title": "V/U/SHF latest in 224",
 "time": { "from": "now-144h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "type": "stat",
   "description": "90m",
   "gridPos": { "h": 2, "w": 8, "x": 0, "y": 0 },
   "repeat": "range",
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "delta(pskreporter_spots_received_total[90m]) + delta(pskreporter_spots_sent_total[90m]) + delta(pskreporter_spots_local_total[90m])",
     "legendFormat": "{{band}}"
    }
   ]
  },
  {
   "type": "stat",
   "description": "3h",
   "gridPos": { "h": 2, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "delta(pskreporter_spots_received_total[3h]) + delta(pskreporter_spots_sent_total[3h]) + delta(pskreporter_spots_local_total[3h])",
     "legendFormat": "{{band}}"
    }
   ]
  },
  {
   "type": "stat",
   "description": "6h",
   "gridPos": { "h": 2, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "delta(pskreporter_spots_received_total[6h]) + delta(pskreporter_spots_sent_total[6h]) + delta(pskreporter_spots_local_total[6h])",
     "legendFormat": "{{band}}"
    }
   ]
  },
  {
   "title": "Received",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "s/h" } },
   "targets": [
    {
     "expr": "delta(pskreporter_spots_received_total[1h])",
     "legendFormat": "{{band}}"
    }
   ]
  },
  {
   "title": "Sent",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s/h" } },
   "targets": [
    {
     "expr": "delta(pskreporter_spots_sent_total[1h])",
     "legendFormat": "{{band}}"
    }
   ]
  },
  {
   "title": "Local",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s/h" } },
   "targets": [
    {
     "expr": "delta(pskreporter_spots_local_total[1h])",
     "legendFormat": "{{band}}"
    }
   ]
  }
 ]
}